CREATE TABLE Lecture
(
    L_ID                   SERIAL PRIMARY KEY,
    L_NAME                 VARCHAR(100) NOT NULL,
    L_CONTENT              TEXT,
    L_VISIBILITY           BOOLEAN      NOT NULL DEFAULT FALSE,
    L_BLOCK                INTEGER      NOT NULL REFERENCES Block (B_ID),
    L_LECTURE_NEXT_ID      INTEGER REFERENCES Lecture (L_ID),
    L_TESTMETERIAL_NEXT_ID INTEGER REFERENCES TestMaterial (T_ID),
    CONSTRAINT L_NEXT_ONLYONE CHECK ( L_LECTURE_NEXT_ID IS NULL OR L_TESTMETERIAL_NEXT_ID IS NULL )
);