CREATE TABLE Attempt
(
    A_ID      SERIAL PRIMARY KEY,
    A_CONTENT TEXT    NOT NULL,
    A_MARK    NUMERIC(4) CHECK (A_MARK >= 0),
    A_DATE    DATE    NOT NULL DEFAULT NOW(),
    A_AUTHOR  INTEGER NOT NULL REFERENCES Client (U_ID),
    A_CHECKER INTEGER REFERENCES Client (U_ID),
    A_TASK    INTEGER NOT NULL REFERENCES TestMaterial (T_ID)
);