CREATE TABLE Lecture
(
    L_ID         SERIAL PRIMARY KEY,
    L_NAME       VARCHAR(100) NOT NULL,
    L_CONTENT    TEXT,
    L_VISIBILITY BOOLEAN      NOT NULL DEFAULT FALSE,
    L_BLOCK      INTEGER      NOT NULL REFERENCES Block (B_ID),
    L_EXTEND     INTEGER      NOT NULL REFERENCES TestMaterial (T_ID),
    L_NEXT_ID    INTEGER REFERENCES Lecture (L_ID)
);