CREATE TABLE TestMaterial
(
    T_ID         SERIAL PRIMARY KEY,
    T_NAME       VARCHAR(100) NOT NULL,
    T_TASK       TEXT         NOT NULL,
    T_MAX        INTEGER      NOT NULL CHECK ( T_MAX >= 0 ),
    T_DURATION   INTERVAL CHECK ( T_DURATION > '0'::INTERVAL ),
    T_VISIBILITY BOOLEAN      NOT NULL DEFAULT FALSE,
    T_EXTEND     INTEGER      NOT NULL REFERENCES lecture (l_id)
);