CREATE TABLE Block
(
    B_ID         SERIAL PRIMARY KEY,
    B_THEME      VARCHAR(100) NOT NULL,
    B_VISIBILITY BOOLEAN      NOT NULL DEFAULT FALSE,
    B_COURSE     INTEGER      NOT NULL REFERENCES Course (C_ID),
    B_NEXT_ID    INTEGER REFERENCES Block (B_ID)
);